version: 2.1
jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine.311
     steps:
       - checkout
       - add_ssh_keys:
           fingerprints: [    ]
       - run:
           name: Install dependencies
           command: |
             apk add -update ansible
       - run:
           name: Configure server
           command: |
             ansible-playbook -i inventory.txt playbook.yml
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
