version: 2.1
jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy --template-file bucket.yml --stack-name "mystack-${CIRCLE_WORKFLOW_ID:0:7}" --parameter-overrides Name="${CIRCLE_WORKFLOW_ID:0:7}"
      
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
            --template-file cloudformation.yml \
            --stack-name cloudfront \
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}"  
    




workflows:
  default:
    jobs:
      - create_and_deploy_front_end
      - promote_to_production

